export type NavigationLocale = "zh" | "en"

export type NavigationPlatform = "web" | "windows" | "macos" | "linux" | "mobile"

export type NavigationFeature = "openSource" | "crossPlatform" | "localFirst"

export type NavigationCategory =
  | "productivity"
  | "development"
  | "ai"
  | "design"
  | "utilities"
  | "knowledge"
  | "communication"
  | "media"
  | "network"
  | "gaming"

export interface LocalizedText {
  zh: string
  en: string
}

export interface NavigationItem {
  id: string
  name: string
  description: LocalizedText
  url: string
  icon: string
  iconUrl?: string
  platforms: NavigationPlatform[]
  category: NavigationCategory
  tags: string[]
  openSource?: boolean
  localFirst?: boolean
  accent: string
  featured?: "wide" | "tall"
}

export interface NavigationFilter {
  id: NavigationPlatform | "all"
  label: LocalizedText
  icon: string
}

export interface NavigationFeatureFilter {
  id: NavigationFeature
  label: LocalizedText
  icon: string
}

export const platformFilters: NavigationFilter[] = [
  { id: "all", label: { zh: "全部", en: "All" }, icon: "lucide:orbit" },
  { id: "web", label: { zh: "常用网站", en: "Web" }, icon: "lucide:globe-2" },
  { id: "windows", label: { zh: "Windows", en: "Windows" }, icon: "ri:windows-fill" },
  { id: "macos", label: { zh: "macOS", en: "macOS" }, icon: "wpf:macos" },
  { id: "linux", label: { zh: "Linux", en: "Linux" }, icon: "mdi:linux" },
  { id: "mobile", label: { zh: "移动端", en: "Mobile" }, icon: "lucide:smartphone" },
]

export const featureFilters: NavigationFeatureFilter[] = [
  { id: "openSource", label: { zh: "开源", en: "Open source" }, icon: "lucide:code-2" },
  { id: "crossPlatform", label: { zh: "跨平台", en: "Cross-platform" }, icon: "lucide:waypoints" },
  { id: "localFirst", label: { zh: "本地优先", en: "Local-first" }, icon: "lucide:hard-drive" },
]

export const categoryLabels: Record<NavigationCategory, LocalizedText> = {
  productivity: { zh: "效率", en: "Productivity" },
  development: { zh: "开发", en: "Development" },
  ai: { zh: "AI", en: "AI" },
  design: { zh: "设计", en: "Design" },
  utilities: { zh: "工具", en: "Utilities" },
  knowledge: { zh: "知识", en: "Knowledge" },
  communication: { zh: "通信", en: "Communication" },
  media: { zh: "影音", en: "Media" },
  network: { zh: "网络", en: "Network" },
  gaming: { zh: "游戏", en: "Gaming" },
}

export const navigationItems: NavigationItem[] = [
  {
    id: "raycast",
    name: "Raycast",
    description: { zh: "用键盘快速启动应用、搜索文件与执行自动化。", en: "Launch apps, find files, and run automations from the keyboard." },
    url: "https://www.raycast.com/",
    icon: "simple-icons:raycast",
    platforms: ["macos", "windows"],
    category: "productivity",
    tags: ["Launcher", "Workflow"],
    accent: "#ff6363",
    featured: "wide",
  },
  {
    id: "powertoys",
    name: "PowerToys",
    description: { zh: "微软为 Windows 提供的窗口、键盘和文件效率工具集。", en: "Microsoft's collection of window, keyboard, and file utilities." },
    url: "https://learn.microsoft.com/windows/powertoys/",
    icon: "simple-icons:windows11",
    platforms: ["windows"],
    category: "utilities",
    tags: ["Microsoft", "Open Source"],
    openSource: true,
    localFirst: true,
    accent: "#4aa7ff",
    featured: "tall",
  },
  {
    id: "obsidian",
    name: "Obsidian",
    description: { zh: "以本地 Markdown 文件构建可连接的个人知识库。", en: "Build a connected personal knowledge base with local Markdown files." },
    url: "https://obsidian.md/",
    icon: "simple-icons:obsidian",
    platforms: ["windows", "macos", "linux", "mobile"],
    category: "knowledge",
    tags: ["Notes", "Markdown"],
    localFirst: true,
    accent: "#a88bfa",
    featured: "wide",
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    description: { zh: "用于问答、写作、分析与多模态创作的 AI 助手。", en: "An AI assistant for answers, writing, analysis, and multimodal creation." },
    url: "https://chatgpt.com/",
    icon: "simple-icons:openai",
    platforms: ["web", "windows", "macos", "mobile"],
    category: "ai",
    tags: ["Assistant", "Multimodal"],
    accent: "#10a37f",
    featured: "wide",
  },
  {
    id: "claude",
    name: "Claude",
    description: { zh: "适合长文本理解、写作、研究与编程协作的 AI 助手。", en: "An AI assistant for long-form understanding, writing, research, and coding." },
    url: "https://claude.ai/",
    icon: "simple-icons:claude",
    platforms: ["web", "windows", "macos", "mobile"],
    category: "ai",
    tags: ["Assistant", "Research"],
    accent: "#d97757",
  },
  {
    id: "ollama",
    name: "Ollama",
    description: { zh: "在本地运行和管理开源大语言模型。", en: "Run and manage open-source large language models locally." },
    url: "https://ollama.com/",
    icon: "simple-icons:ollama",
    platforms: ["windows", "macos", "linux"],
    category: "ai",
    tags: ["Local AI", "Open Source"],
    openSource: true,
    localFirst: true,
    accent: "#8a95a5",
  },
  {
    id: "vscode",
    name: "Visual Studio Code",
    description: { zh: "轻量、可扩展并支持多平台的代码编辑器。", en: "A lightweight, extensible code editor available across platforms." },
    url: "https://code.visualstudio.com/",
    icon: "devicon:vscode",
    platforms: ["windows", "macos", "linux"],
    category: "development",
    tags: ["Editor", "Microsoft"],
    localFirst: true,
    accent: "#3aa7e8",
  },
  {
    id: "localsend",
    name: "LocalSend",
    description: { zh: "无需账户，在局域网内跨平台传输文件。", en: "Transfer files across nearby devices without an account." },
    url: "https://localsend.org/",
    icon: "lucide:send",
    platforms: ["windows", "macos", "linux", "mobile"],
    category: "utilities",
    tags: ["Transfer", "Open Source"],
    openSource: true,
    localFirst: true,
    accent: "#36c9a0",
  },
  {
    id: "iterm2",
    name: "iTerm2",
    description: { zh: "面向 macOS 的高可配置终端模拟器。", en: "A highly configurable terminal emulator for macOS." },
    url: "https://iterm2.com/",
    icon: "simple-icons:iterm2",
    platforms: ["macos"],
    category: "development",
    tags: ["Terminal", "Open Source"],
    openSource: true,
    localFirst: true,
    accent: "#7d8b98",
  },
  {
    id: "everything",
    name: "Everything",
    description: { zh: "在 Windows 上近乎即时地按名称查找文件。", en: "Find files by name almost instantly on Windows." },
    url: "https://www.voidtools.com/",
    icon: "lucide:search-code",
    platforms: ["windows"],
    category: "utilities",
    tags: ["Search", "Files"],
    localFirst: true,
    accent: "#f0c44f",
  },
  {
    id: "github",
    name: "GitHub",
    description: { zh: "托管代码、协作开发并发现开源项目。", en: "Host code, collaborate, and discover open-source projects." },
    url: "https://github.com/",
    icon: "simple-icons:github",
    platforms: ["web"],
    category: "development",
    tags: ["Git", "Collaboration"],
    accent: "#8b949e",
    featured: "wide",
  },
  {
    id: "iconify",
    name: "Iconify",
    description: { zh: "统一搜索和使用多个开源图标集合。", en: "Search and use many open-source icon sets through one interface." },
    url: "https://icon-sets.iconify.design/",
    icon: "simple-icons:iconify",
    platforms: ["web"],
    category: "design",
    tags: ["Icons", "Open Source"],
    openSource: true,
    accent: "#1769aa",
  },
  {
    id: "tinypng",
    name: "TinyPNG",
    description: { zh: "在线压缩 WebP、PNG 和 JPEG 图片。", en: "Compress WebP, PNG, and JPEG images online." },
    url: "https://tinypng.com/",
    icon: "lucide:images",
    platforms: ["web"],
    category: "utilities",
    tags: ["Compress", "Image"],
    accent: "#59b875",
  },
  {
    id: "hvoyai",
    name: "禾维 AI",
    description: { zh: "检测 Claude、GPT 与 Gemini API，并对中转服务进行实测比较。", en: "Test Claude, GPT, and Gemini APIs and compare relay providers with live measurements." },
    url: "https://www.hvoyai.com/",
    icon: "lucide:scan-search",
    iconUrl: "https://www.hvoyai.com/favicoin.svg",
    platforms: ["web"],
    category: "ai",
    tags: ["API", "Benchmark"],
    accent: "#27b3ff",
  },
  {
    id: "cursor-byok",
    name: "cursor-byok",
    description: { zh: "在本地将 Cursor 连接到自定义模型 API，并保留 Agent 工具能力。", en: "Connect Cursor to custom model APIs locally while preserving Agent tooling." },
    url: "https://github.com/leookun/cursor-byok",
    icon: "simple-icons:cursor",
    platforms: ["windows", "macos", "linux"],
    category: "ai",
    tags: ["Cursor", "Model Gateway"],
    openSource: true,
    localFirst: true,
    accent: "#8b9cff",
  },
  {
    id: "cc-switch",
    name: "CC Switch",
    description: { zh: "统一管理多种 AI 编程工具的供应商、模型、MCP、技能与用量。", en: "Manage providers, models, MCP, skills, and usage across AI coding tools." },
    url: "https://ccswitch.io/zh/",
    icon: "lucide:refresh-cw",
    iconUrl: "https://ccswitch.io/favicon.ico",
    platforms: ["windows", "macos", "linux"],
    category: "development",
    tags: ["AI Coding", "Configuration"],
    openSource: true,
    localFirst: true,
    accent: "#6d8cff",
  },
  {
    id: "codex-plus-plus",
    name: "Codex++",
    description: { zh: "集中管理 Codex 的供应商、模型、会话、插件、脚本与界面增强。", en: "Manage Codex providers, models, sessions, plugins, scripts, and interface enhancements." },
    url: "https://codexpp.cc/",
    icon: "lucide:blocks",
    iconUrl: "https://codexpp.cc/images/codex-plus-plus.png",
    platforms: ["windows", "macos"],
    category: "development",
    tags: ["Codex", "Manager"],
    openSource: true,
    localFirst: true,
    accent: "#8b5cf6",
  },
  {
    id: "hugging-face",
    name: "Hugging Face",
    description: { zh: "发现、共享并协作开发机器学习模型、数据集与应用。", en: "Discover, share, and collaborate on machine-learning models, datasets, and apps." },
    url: "https://huggingface.co/",
    icon: "simple-icons:huggingface",
    iconUrl: "https://huggingface.co/favicon.ico",
    platforms: ["web"],
    category: "ai",
    tags: ["Models", "Datasets"],
    accent: "#ffcc4d",
  },
  {
    id: "ui-ux-pro-max",
    name: "UI/UX Pro Max",
    description: { zh: "搜索界面风格、配色、字体、图表和 UX 规范，为 AI 编程提供设计建议。", en: "Search UI styles, palettes, fonts, charts, and UX guidance for AI-assisted coding." },
    url: "https://www.uupm.cc/",
    icon: "lucide:palette",
    iconUrl: "https://www.uupm.cc/icon.svg",
    platforms: ["web"],
    category: "ai",
    tags: ["UI/UX", "Design System"],
    accent: "#ec4899",
  },
  {
    id: "can-i-run-ai",
    name: "CanIRun.ai",
    description: { zh: "根据 GPU 和内存评估本机可运行的开放模型及量化版本。", en: "Match open models and quantizations to your GPU and available memory." },
    url: "https://www.canirun.ai/",
    icon: "lucide:gauge",
    iconUrl: "https://www.canirun.ai/favicon.ico",
    platforms: ["web"],
    category: "ai",
    tags: ["Local AI", "Hardware"],
    accent: "#22c55e",
  },
  {
    id: "comfyui-docs",
    name: "ComfyUI Docs",
    description: { zh: "ComfyUI 节点式图像、视频、音频与 3D 生成工作流的官方文档。", en: "Official guides for ComfyUI node-based image, video, audio, and 3D workflows." },
    url: "https://docs.comfy.org/",
    icon: "lucide:workflow",
    iconUrl: "https://docs.comfy.org/favicon.ico",
    platforms: ["web"],
    category: "ai",
    tags: ["ComfyUI", "Docs"],
    openSource: true,
    accent: "#5b8cff",
  },
  {
    id: "money-printer-turbo",
    name: "MoneyPrinterTurbo",
    description: { zh: "根据主题或关键词自动生成脚本、素材、字幕、配乐与高清短视频。", en: "Generate scripts, footage, subtitles, music, and HD short videos from a topic or keyword." },
    url: "https://github.com/harry0703/MoneyPrinterTurbo",
    icon: "lucide:clapperboard",
    platforms: ["windows", "macos", "linux"],
    category: "ai",
    tags: ["Video Generation", "Automation"],
    openSource: true,
    localFirst: true,
    accent: "#ef4444",
  },
  {
    id: "openmontage",
    name: "OpenMontage",
    description: { zh: "让 AI 编程助手完成调研、脚本、分镜、配音、剪辑与渲染的开源视频制作系统。", en: "An open-source video production system that lets AI coding assistants research, script, storyboard, narrate, edit, and render." },
    url: "https://www.openmontage.video/",
    icon: "lucide:film",
    platforms: ["windows", "macos", "linux"],
    category: "ai",
    tags: ["Agent", "Video Production"],
    openSource: true,
    localFirst: true,
    accent: "#f97316",
  },
  {
    id: "diagram-design",
    name: "Diagram Design",
    description: { zh: "为 Claude Code、Codex 等 AI 编程助手提供 38 种可编辑的专业图表设计模板。", en: "A library of 38 editable editorial diagram templates for AI coding assistants such as Claude Code and Codex." },
    url: "https://cathrynlavery.github.io/diagram-design/",
    icon: "lucide:git-fork",
    platforms: ["web"],
    category: "ai",
    tags: ["Diagrams", "AI Coding"],
    openSource: true,
    accent: "#8b5cf6",
  },
  {
    id: "gpt-image-2-api",
    name: "GPT Image 2 API",
    description: { zh: "通过网页和 API 生成、编辑并导出营销与产品图像。", en: "Generate, edit, and export marketing and product images through the web and API." },
    url: "https://gptimage2api.net/",
    icon: "lucide:image-plus",
    iconUrl: "https://gptimage2api.net/favicon.ico",
    platforms: ["web"],
    category: "ai",
    tags: ["Image Generation", "API"],
    accent: "#14b8a6",
  },
  {
    id: "dreamskin",
    name: "DreamSkin",
    description: { zh: "在浏览器中预览、制作并导出 Codex 桌面端主题。", en: "Preview, create, and export themes for the Codex desktop app in the browser." },
    url: "https://www.dreamskin.cc/",
    icon: "lucide:sparkles",
    iconUrl: "https://www.dreamskin.cc/favicon.svg",
    platforms: ["web"],
    category: "design",
    tags: ["Codex", "Themes"],
    accent: "#a855f7",
  },
  {
    id: "homebrew",
    name: "Homebrew",
    description: { zh: "面向 macOS 和 Linux 的命令行软件包管理器。", en: "A command-line package manager for macOS and Linux." },
    url: "https://brew.sh/",
    icon: "simple-icons:homebrew",
    platforms: ["macos", "linux"],
    category: "development",
    tags: ["Package Manager", "CLI"],
    openSource: true,
    localFirst: true,
    accent: "#fbb040",
  },
  {
    id: "macports",
    name: "MacPorts",
    description: { zh: "在 macOS 上编译、安装和升级开源软件的包管理系统。", en: "Build, install, and upgrade open-source software on macOS." },
    url: "https://ports.macports.org/",
    icon: "lucide:package-open",
    iconUrl: "https://ports.macports.org/static/images/favicon.ico",
    platforms: ["macos"],
    category: "development",
    tags: ["Package Manager", "Open Source"],
    openSource: true,
    localFirst: true,
    accent: "#2d8c4f",
  },
  {
    id: "paste",
    name: "Paste",
    description: { zh: "在 Mac、iPhone 与 iPad 间保存、搜索和同步剪贴板历史。", en: "Save, search, and sync clipboard history across Mac, iPhone, and iPad." },
    url: "https://pasteapp.io/",
    icon: "lucide:clipboard-list",
    iconUrl: "https://pasteapp.io/icon.png?icon.16-14bea0soxq.png",
    platforms: ["macos", "mobile"],
    category: "productivity",
    tags: ["Clipboard", "iCloud"],
    localFirst: true,
    accent: "#6c5ce7",
  },
  {
    id: "textsniper",
    name: "TextSniper",
    description: { zh: "在 macOS 屏幕上框选文字，并通过本地 OCR 复制到剪贴板。", en: "Capture text from any area of the macOS screen with on-device OCR." },
    url: "https://textsniper.app/",
    icon: "lucide:scan-text",
    iconUrl: "https://textsniper.app/favicon.ico",
    platforms: ["macos"],
    category: "productivity",
    tags: ["OCR", "Clipboard"],
    localFirst: true,
    accent: "#ff5a5f",
  },
  {
    id: "cleanshot-x",
    name: "CleanShot X",
    description: { zh: "面向 macOS 的截图、录屏、标注和快速分享工具。", en: "A macOS toolkit for screenshots, recordings, annotation, and sharing." },
    url: "https://cleanshot.com/",
    icon: "lucide:camera",
    iconUrl: "https://cleanshot.com/favicon@2x.png",
    platforms: ["macos"],
    category: "productivity",
    tags: ["Screenshot", "Recording"],
    localFirst: true,
    accent: "#4c8dff",
  },
  {
    id: "pesty",
    name: "Pesty",
    description: { zh: "原生、免费且开源的 macOS 剪贴板历史与固定内容管理器。", en: "A native, free, open-source clipboard history and pinboard manager for macOS." },
    url: "https://www.moamenbasel.com/pesty/",
    icon: "lucide:clipboard-copy",
    iconUrl: "https://www.moamenbasel.com/pesty/assets/icon.png",
    platforms: ["macos"],
    category: "productivity",
    tags: ["Clipboard", "Open Source"],
    openSource: true,
    localFirst: true,
    accent: "#f97316",
  },
  {
    id: "iina",
    name: "IINA",
    description: { zh: "为现代 macOS 设计的开源媒体播放器。", en: "An open-source media player designed for modern macOS." },
    url: "https://iina.io/",
    icon: "lucide:play",
    iconUrl: "https://iina.io/images/favicon-32x32.png",
    platforms: ["macos"],
    category: "media",
    tags: ["Video", "Open Source"],
    openSource: true,
    localFirst: true,
    accent: "#38bdf8",
  },
  {
    id: "hidden",
    name: "Hidden Bar",
    description: { zh: "隐藏和整理 macOS 菜单栏中过多的应用图标。", en: "Hide and organize excess application icons in the macOS menu bar." },
    url: "https://github.com/dwarvesf/hidden",
    icon: "lucide:panel-top-close",
    iconUrl: "https://raw.githubusercontent.com/dwarvesf/hidden/develop/img/icon_512%402x.png",
    platforms: ["macos"],
    category: "utilities",
    tags: ["Menu Bar", "Open Source"],
    openSource: true,
    localFirst: true,
    accent: "#64748b",
  },
  {
    id: "keka",
    name: "Keka",
    description: { zh: "支持多种格式的 macOS 文件压缩与解压工具。", en: "Compress and extract many archive formats on macOS." },
    url: "https://www.keka.io/en/",
    icon: "lucide:archive",
    iconUrl: "https://www.keka.io/img/Keka-Square-32x32@2x.png",
    platforms: ["macos"],
    category: "utilities",
    tags: ["Archive", "Compression"],
    openSource: true,
    localFirst: true,
    accent: "#8b5e3c",
  },
  {
    id: "mac-app-cleaner",
    name: "App Cleaner & Uninstaller",
    description: { zh: "完整卸载 Mac 应用，并清理其残留文件和扩展。", en: "Remove Mac apps completely, including leftover files and extensions." },
    url: "https://nektony.com/mac-app-cleaner",
    icon: "lucide:trash-2",
    platforms: ["macos"],
    category: "utilities",
    tags: ["Uninstaller", "Cleanup"],
    localFirst: true,
    accent: "#18a999",
  },
  {
    id: "airbuddy",
    name: "AirBuddy",
    description: { zh: "在 Mac 上查看和管理 AirPods 等 Apple 与蓝牙设备的状态。", en: "View and manage AirPods and other Apple or Bluetooth devices from your Mac." },
    url: "https://v3.airbuddy.app/",
    icon: "lucide:bluetooth",
    iconUrl: "https://v3.airbuddy.app/favicon.ico",
    platforms: ["macos"],
    category: "utilities",
    tags: ["AirPods", "Bluetooth"],
    localFirst: true,
    accent: "#5ac8fa",
  },
  {
    id: "elmedia-player",
    name: "Elmedia Player",
    description: { zh: "支持多种音视频格式、字幕和流媒体播放的 Mac 播放器。", en: "A Mac player for many audio-video formats, subtitles, and streaming." },
    url: "https://www.elmedia-video-player.com/",
    icon: "lucide:circle-play",
    iconUrl: "https://www.elmedia-video-player.com/favicon.ico",
    platforms: ["macos"],
    category: "media",
    tags: ["Video", "Streaming"],
    localFirst: true,
    accent: "#ff3b30",
  },
  {
    id: "boring-notch",
    name: "Boring Notch",
    description: { zh: "将 MacBook 刘海区域扩展为音乐、文件和快捷控制中心。", en: "Turn the MacBook notch into a hub for music, files, and quick controls." },
    url: "https://github.com/TheBoredTeam/boring.notch",
    icon: "lucide:panel-top",
    iconUrl: "https://theboring.name/assets/icons/boring-notch.png",
    platforms: ["macos"],
    category: "utilities",
    tags: ["Notch", "Open Source"],
    openSource: true,
    localFirst: true,
    accent: "#71717a",
  },
  {
    id: "massgrave",
    name: "Microsoft Activation Scripts",
    description: { zh: "提供 Windows 与 Office 激活脚本及相关技术文档；使用前应确认授权合规。", en: "Windows and Office activation scripts and technical documentation; verify licensing compliance before use." },
    url: "https://massgrave.dev/",
    icon: "lucide:key-round",
    platforms: ["windows"],
    category: "utilities",
    tags: ["Windows", "Activation"],
    openSource: true,
    localFirst: true,
    accent: "#2563eb",
  },
  {
    id: "switchhosts",
    name: "SwitchHosts",
    description: { zh: "在桌面端快速切换和管理多套 Hosts 配置。", en: "Switch and manage multiple Hosts configurations from a desktop app." },
    url: "https://switchhosts.app/",
    icon: "lucide:network",
    iconUrl: "https://switchhosts.app/favicon.ico",
    platforms: ["windows", "macos", "linux"],
    category: "development",
    tags: ["Hosts", "Network"],
    openSource: true,
    localFirst: true,
    accent: "#4caf50",
  },
  {
    id: "twinkle-tray",
    name: "Twinkle Tray",
    description: { zh: "从 Windows 系统托盘统一控制外接显示器亮度。", en: "Control external monitor brightness from the Windows system tray." },
    url: "https://twinkletray.com/",
    icon: "lucide:sun-medium",
    iconUrl: "https://twinkletray.com/favicon.ico",
    platforms: ["windows"],
    category: "utilities",
    tags: ["Display", "Brightness"],
    openSource: true,
    localFirst: true,
    accent: "#f59e0b",
  },
  {
    id: "sandboxie-plus",
    name: "Sandboxie Plus",
    description: { zh: "在 Windows 沙盒中隔离运行应用和浏览器。", en: "Run applications and browsers in isolated Windows sandboxes." },
    url: "https://sandboxie-plus.com/",
    icon: "lucide:box",
    iconUrl: "https://sandboxie-plus.com/favicon.ico",
    platforms: ["windows"],
    category: "utilities",
    tags: ["Sandbox", "Security"],
    openSource: true,
    localFirst: true,
    accent: "#f4b942",
  },
  {
    id: "mactype",
    name: "MacType",
    description: { zh: "调整 Windows 字体栅格化方式，改善屏幕文字渲染。", en: "Improve on-screen text rendering by customizing font rasterization on Windows." },
    url: "https://www.mactype.net/",
    icon: "lucide:type",
    platforms: ["windows"],
    category: "utilities",
    tags: ["Fonts", "Rendering"],
    openSource: true,
    localFirst: true,
    accent: "#0ea5e9",
  },
  {
    id: "telegram",
    name: "Telegram",
    description: { zh: "支持多设备同步、群组、频道与文件传输的即时通信平台。", en: "Messaging with multi-device sync, groups, channels, and file sharing." },
    url: "https://telegram.org/",
    icon: "simple-icons:telegram",
    platforms: ["windows", "macos", "linux", "mobile"],
    category: "communication",
    tags: ["Messaging", "Channels"],
    accent: "#26a5e4",
  },
  {
    id: "discord",
    name: "Discord",
    description: { zh: "面向社区与团队的文字、语音、视频和频道通信平台。", en: "Text, voice, video, and channel-based communication for communities and teams." },
    url: "https://discord.com/",
    icon: "simple-icons:discord",
    platforms: ["windows", "macos", "linux", "mobile"],
    category: "communication",
    tags: ["Community", "Voice"],
    accent: "#5865f2",
  },
  {
    id: "ffmpeg",
    name: "FFmpeg",
    description: { zh: "录制、转换、处理和流式传输音视频的开源工具集。", en: "An open-source toolkit for recording, converting, processing, and streaming media." },
    url: "https://ffmpeg.org/",
    icon: "simple-icons:ffmpeg",
    platforms: ["windows", "macos", "linux"],
    category: "media",
    tags: ["Audio/Video", "CLI"],
    openSource: true,
    localFirst: true,
    accent: "#007808",
  },
  {
    id: "foobar2000",
    name: "foobar2000",
    description: { zh: "轻量、可定制并支持广泛格式的本地音频播放器。", en: "A lightweight, customizable local audio player with broad format support." },
    url: "https://www.foobar2000.org/",
    icon: "lucide:music",
    iconUrl: "https://www.foobar2000.org/favicon.ico",
    platforms: ["windows", "macos", "mobile"],
    category: "media",
    tags: ["Audio", "Player"],
    localFirst: true,
    accent: "#c0c0c0",
  },
  {
    id: "potplayer",
    name: "PotPlayer",
    description: { zh: "支持丰富格式、字幕和硬件加速的 Windows 媒体播放器。", en: "A Windows media player with broad format, subtitle, and hardware acceleration support." },
    url: "http://www.potplayercn.com/",
    icon: "lucide:play-square",
    platforms: ["windows"],
    category: "media",
    tags: ["Video", "Player"],
    localFirst: true,
    accent: "#8b5cf6",
  },
  {
    id: "sharex",
    name: "ShareX",
    description: { zh: "Windows 上的截图、录屏、标注、OCR 与自动上传工具。", en: "Capture, record, annotate, OCR, and upload from Windows." },
    url: "https://getsharex.com/",
    icon: "simple-icons:sharex",
    platforms: ["windows"],
    category: "productivity",
    tags: ["Screenshot", "Automation"],
    openSource: true,
    localFirst: true,
    accent: "#2b9bd7",
  },
  {
    id: "honeyview",
    name: "Honeyview",
    description: { zh: "快速浏览常见图片、压缩包图像和照片信息的 Windows 查看器。", en: "A fast Windows viewer for images, archived pictures, and photo metadata." },
    url: "https://en.bandisoft.com/honeyview/",
    icon: "lucide:image",
    platforms: ["windows"],
    category: "media",
    tags: ["Image", "Viewer"],
    localFirst: true,
    accent: "#f59e0b",
  },
  {
    id: "termius",
    name: "Termius",
    description: { zh: "跨桌面和移动设备管理 SSH、SFTP 与服务器连接。", en: "Manage SSH, SFTP, and server connections across desktop and mobile devices." },
    url: "https://termius.com/",
    icon: "simple-icons:termius",
    platforms: ["windows", "macos", "linux", "mobile"],
    category: "development",
    tags: ["SSH", "SFTP"],
    accent: "#2d2d2d",
  },
  {
    id: "beyond-compare",
    name: "Beyond Compare",
    description: { zh: "比较、同步与合并文件、目录、归档和远程数据。", en: "Compare, synchronize, and merge files, folders, archives, and remote data." },
    url: "https://www.scootersoftware.com/",
    icon: "lucide:columns-3",
    iconUrl: "https://www.scootersoftware.com/favicon.ico",
    platforms: ["windows", "macos", "linux"],
    category: "development",
    tags: ["Diff", "Sync"],
    localFirst: true,
    accent: "#ef4444",
  },
  {
    id: "testufo",
    name: "TestUFO",
    description: { zh: "在浏览器中测试显示器刷新率、帧率与运动清晰度。", en: "Test display refresh rate, frame rate, and motion clarity in the browser." },
    url: "https://testufo.com/framerates#count=6&background=stars&pps=960",
    icon: "lucide:monitor-up",
    platforms: ["web"],
    category: "utilities",
    tags: ["Display", "Benchmark"],
    accent: "#22d3ee",
  },
  {
    id: "linux-command",
    name: "Linux Command",
    description: { zh: "按名称和分类查询 Linux 命令、参数与使用示例。", en: "Browse Linux commands, options, and examples by name or category." },
    url: "https://wangchujiang.com/linux-command/",
    icon: "mdi:linux",
    platforms: ["web"],
    category: "knowledge",
    tags: ["Linux", "Reference"],
    openSource: true,
    accent: "#f5c542",
  },
  {
    id: "fluxdown",
    name: "FluxDown",
    description: { zh: "支持 HTTP、FTP、BitTorrent 与流媒体的开源多协议下载管理器。", en: "An open-source multi-protocol download manager for HTTP, FTP, BitTorrent, and streams." },
    url: "https://fluxdown.zerx.dev/",
    icon: "lucide:download",
    iconUrl: "https://fluxdown.zerx.dev/favicon.ico",
    platforms: ["windows", "macos", "linux", "mobile"],
    category: "utilities",
    tags: ["Downloader", "Open Source"],
    openSource: true,
    localFirst: true,
    accent: "#3b82f6",
  },
  {
    id: "fan-control",
    name: "Fan Control",
    description: { zh: "通过传感器曲线控制 Windows 电脑的 CPU、GPU 与机箱风扇。", en: "Control CPU, GPU, and case fans on Windows with sensor-based curves." },
    url: "https://getfancontrol.com/",
    icon: "lucide:fan",
    iconUrl: "https://getfancontrol.com/favicon.svg",
    platforms: ["windows"],
    category: "utilities",
    tags: ["Hardware", "Cooling"],
    openSource: true,
    localFirst: true,
    accent: "#06b6d4",
  },
  {
    id: "scamalytics",
    name: "Scamalytics",
    description: { zh: "检测 IP 地址的代理、匿名网络与欺诈风险信号。", en: "Check IP addresses for proxy, anonymity, and fraud-risk signals." },
    url: "https://scamalytics.com/",
    icon: "lucide:shield-check",
    platforms: ["web"],
    category: "network",
    tags: ["IP Check", "Fraud Risk"],
    accent: "#0f766e",
  },
  {
    id: "fast",
    name: "FAST.com",
    description: { zh: "由 Netflix 提供的简洁网络下载速度与延迟测试。", en: "A simple internet download-speed and latency test powered by Netflix." },
    url: "https://fast.com/",
    icon: "lucide:gauge",
    iconUrl: "https://fast.com/favicon.ico",
    platforms: ["web", "mobile"],
    category: "network",
    tags: ["Speed Test", "Netflix"],
    accent: "#e50914",
  },
  {
    id: "speedtest",
    name: "Speedtest by Ookla",
    description: { zh: "测试网络下载、上传、延迟和连接质量。", en: "Measure network download, upload, latency, and connection quality." },
    url: "https://www.speedtest.net/",
    icon: "lucide:activity",
    iconUrl: "https://www.speedtest.net/favicon.ico",
    platforms: ["web", "windows", "macos", "linux", "mobile"],
    category: "network",
    tags: ["Speed Test", "Diagnostics"],
    accent: "#141526",
  },
  {
    id: "wikihow",
    name: "wikiHow",
    description: { zh: "涵盖生活、技术和实用技能的分步骤图文指南。", en: "Step-by-step illustrated guides for everyday, technical, and practical skills." },
    url: "https://www.wikihow.com/Main-Page",
    icon: "lucide:book-open-check",
    iconUrl: "https://www.wikihow.com/favicon.ico",
    platforms: ["web", "mobile"],
    category: "knowledge",
    tags: ["How-to", "Guides"],
    accent: "#93b874",
  },
  {
    id: "g-generation-eternal",
    name: "SD Gundam G Generation ETERNAL",
    description: { zh: "《SD 高达 G 世代 永恒》的万代南梦宫日文官方网站。", en: "The official Japanese site for SD Gundam G Generation ETERNAL by Bandai Namco." },
    url: "https://gget.ggame.jp/jp/",
    icon: "lucide:gamepad-2",
    iconUrl: "https://gget.ggame.jp/jp/favicon.ico",
    platforms: ["windows", "mobile"],
    category: "gaming",
    tags: ["Gundam", "Official"],
    accent: "#2563eb",
  },
  {
    id: "gget-guide",
    name: "G Generation ETERNAL Guide",
    description: { zh: "面向《SD 高达 G 世代 永恒》玩家的第三方日文资料站。", en: "A third-party Japanese reference site for SD Gundam G Generation ETERNAL players." },
    url: "https://soshage.com/gget/ja",
    icon: "lucide:notebook-tabs",
    platforms: ["web"],
    category: "gaming",
    tags: ["Gundam", "Guide"],
    accent: "#475569",
  },
  {
    id: "tales-channel",
    name: "Tales Channel+",
    description: { zh: "万代南梦宫《传说》系列的官方作品、新闻与活动门户。", en: "The official Bandai Namco portal for Tales series titles, news, and events." },
    url: "https://tales-ch.jp/",
    icon: "lucide:swords",
    iconUrl: "https://tales-ch.jp/favicon.ico",
    platforms: ["web"],
    category: "gaming",
    tags: ["Tales", "Official"],
    accent: "#e11d48",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    description: { zh: "提供 CDN、DNS、安全防护和边缘计算的全球网络平台。", en: "A global network platform for CDN, DNS, security, and edge computing." },
    url: "https://www.cloudflare.com/",
    icon: "simple-icons:cloudflare",
    platforms: ["web"],
    category: "network",
    tags: ["CDN", "Security"],
    accent: "#f38020",
  },
  {
    id: "jsdelivr",
    name: "jsDelivr",
    description: { zh: "面向 npm、GitHub 和开源项目的免费公共 CDN。", en: "A free public CDN for npm, GitHub, and open-source projects." },
    url: "https://www.jsdelivr.com/",
    icon: "simple-icons:jsdelivr",
    platforms: ["web"],
    category: "development",
    tags: ["CDN", "Open Source"],
    openSource: true,
    accent: "#e84d3d",
  },
  {
    id: "g-book-zousho",
    name: "G-BOOK 蔵書",
    description: { zh: "浏览 G-BOOK 网站整理的图书收藏与书目资料。", en: "Browse the book collection and bibliographic resources curated by G-BOOK." },
    url: "https://www.ne.jp/asahi/g-book/zousho/",
    icon: "lucide:library",
    iconUrl: "https://www.ne.jp/asahi/g-book/zousho/favicon.ico",
    platforms: ["web"],
    category: "knowledge",
    tags: ["Books", "Reference"],
    accent: "#b7791f",
  },
  {
    id: "steamtools",
    name: "SteamTools",
    description: { zh: "提供 Steam 相关工具与实用功能的站点。", en: "A collection of tools and utilities for Steam." },
    url: "https://steamtools.net/",
    icon: "simple-icons:steam",
    iconUrl: "https://steamtools.net/favicon.ico",
    platforms: ["web", "windows"],
    category: "gaming",
    tags: ["Steam", "Tools"],
    accent: "#1b9fff",
  },
]